---
- name: httpd
  hosts: all
  tasks:
  - name: Install apache packages 
    yum:
      name: httpd
      state: present
  - name: certifique-se de que o httpd esteja rodando
    service:
      name: httpd 
      state: started
  - name: Abra a porta 80 para acesso http
    firewalld:
      service: http
      permanent: true
      state: enabled
  - name: Reinicie o serviço firewalld para carregar nas alterações do firewall
    service: 
      name: firewalld 
      state: restarted
